### ISSUE TITLE
Urgent bug with children with no ref

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [medhatdawoud/react-change-highlight#17]
**Describe the bug**
When adding children with no ref throw error with message `Cannot read property 'current' of null
    at ShadowChild:32`

**To Reproduce**
Just add child without ref

**Expected behavior**
Ignore changing state in this element

**Screenshots**
![image](https://user-images.githubusercontent.com/14947957/69007741-4a7a9980-094a-11ea-9dfb-b831f0f9e8e8.png)

**Comment by medhatdawoud** [comment]
Nice catch 👍
