### ISSUE TITLE
Detect newly added elements and highlight them as well

### ISSUE THREAD

**Issue by medhatdawoud** [medhatdawoud/react-change-highlight#20]
when we wrap the cart for example in `ChangeHighlight` it highlights the total price as required but the newly added items are not highlighted, and this is important to be highlighted as well

So the expected result is to detect new elements inside the wrap and highlight them as well.

**Comment by EslamHiko** [comment]
Newly added items highlight in this code : 

```javascript
function App() {
  const [counts, setCounts] = useState([0]);

  const countUp = () => {
    setCounts(counts.map((count)=>count+1));
  };

  const addCount = () => {
    setCounts([...counts,0])
  };
  
  return (
    <div className="App">
      <button onClick={countUp}>Count up</button>
      <button onClick={addCount}>add</button>

      <br />
      <ChangeHighlight showAfter={100} hideAfter={2000}>
        {counts.map(count=><h1 ref={React.createRef()}>{count}</h1>)}
      </ChangeHighlight>
    </div>
  );
}
const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by medhatdawoud** [comment]
Still very simple example, make the `h1` element wrapped inside more than one layer and try again, and also we cannot highlight the parent in case on one of the children has a change, this is another issue we need to resolve

**Comment by medhatdawoud** [comment]
this is kind of related to #21
