### ISSUE TITLE
Fix nested ChangeHighlight

### ISSUE THREAD

**Issue by medhatdawoud** [medhatdawoud/react-change-highlight#8]
As a user I might need to highlight a div and some times to highlight a small part of it, or maybe highlight another part differently, this can be done using nested `ChangeHighlight` like this:
```jsx
<ChangeHighlight>
    <div ref="ref1">
        {message1}
        <ChangeHighlight>
          <div ref="ref2">{message2}</div>
        </ChangeHighlight>
    </div>
</ChangeHighlight>
```
with the current implementation, the styling of the top `ChangeHighlight` will override the internal one's style which is not the desirable action in this case.

**Proposal:** we need during creating the shadowDOM to skip the ref element that are wrapped inside another `ChangeHighlight` element.

**Comment by medhatdawoud** [comment]
@EslamHiko can you find another way to generate the ID which is 100% unique ? because I feel that the solution is random and it has a probability of %0.00001 that it can be repeated, just for a more robust solution that people might use for pig applications and you don't know how many instances will be there

**Comment by EslamHiko** [comment]
@medhatdawoud please, Check my PR: https://github.com/medhatdawoud/react-change-highlight/pull/15
